title: Home
tabs:
  content:
    label: Inhalt
    
    columns:
      main:
        width: 1/1
        fields:
          layout:
            type: layout
            layouts:
              - "1/1"
              - "1/2, 1/2"
              - "1/3, 1/3, 1/3"
            settings:
              fields:
                class:
                  type: text
                  width: 1/2
                id:
                  type: text
                  width: 1/2
            fieldsets:
              - heading
              - text
              - image
              - line
  inhalt:
    label: Inhalt
    fields:
      h_1:
        label: Fotos
        type: headline
        numbered: false
      l_foto:
        label: Foto /links
        min: 0
        max: 1
        type: files
        layout: cards
        image:
          ratio: square
          back: white
        query: page.images
        width: 1/3
      l_gap:
        type: gap
        width: 1/6
      r_foto:
        label: Foto / rechts
        min: 0
        max: 1
        type: files
        layout: cards
        image:
          ratio: square
          back: white
        query: page.images
        width: 1/3
      r_gap:
        type: gap
        width: 1/6
      l_bildbeschriftung:
        label: Bildbeschriftung
        type: text
        width: 1/2
      r_bildbeschriftung:
        label: Bildbeschriftung
        type: text
        width: 1/2
      l_untertitel:
        label: Untertitel
        type: text
        width: 1/2
      r_untertitel:
        label: Untertitel
        type: text
        width: 1/2
      line_2:
        type: line
      h_2:
        label: Claim
        type: headline
        numbered: false
      claim_text:
        label: Text
        type: writer
        size: large
        width: 1/2
      line_3:
        type: line
      h_3:
        label: Leistungen
        type: headline
        numbered: false
      leistungen_titel:
        label: Titel
        type: textarea
        size: tiny
        width: 1/3
      leistungen_text:
        label: Text
        type: writer
        size: medium
        width: 2/3
      line_4:
        type: line
      h_4:
        label: Lebenslauf
        type: headline
        numbered: false
      illustration_bild:
        label: Illustration
        min: 0
        max: 1
        type: files
        layout: cards
        image:
          ratio: square
          back: white
        query: page.images
        width: 1/3
      illustration_text:
        label: Text
        type: textarea
        size: tiny
        width: 2/3
        
  seotab: seo